Jmeterrun:
      stage: testjmeter
      variables:
           PROJECT_DIR: /builds/projectpath
          JMETER_PROJECT_DIR: $PROJECT_DIR/docker-jmeter
      image:
           name: justb4/jmeter:latest
           entrypoint: [""]
      before script:
         - apk add --update zip
      script:
         - mkdir -p -m 777 $JMETER_PROJECT_DIR/tests/report/jmeter 
         - /entrypoint.sh -n -t ./testcalls.jmx −1 $JMETER_PROJECT_DIR/tests/report/testresults.log -e -o $JMETER_PROJECT_DIR/tests/report/jmeterreports
         - cd $JMETER_PROJECT_DIR/tests/report
         - zip -r $PROJECT_DIR/jmeter-qa-results.zip . 
     artifacts:
        paths:
          - $PROJECT_DIR/jmeter-qa-results.zip
        when: on success
